# Generated by Django 4.2.8 on 2024-06-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_about_self_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
