# Generated by Django 4.2.8 on 2024-05-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='liked_by',
        ),
    ]
